services:
  epic-free-games:
    build: .
    container_name: epic-free-games
    restart: "no"
    volumes:
      - /mnt/user/appdata/epic-free-games/data:/app/data
    environment:
      - DATA_DIR=/app/data
      - TZ=Asia/Shanghai
      - EG_EMAIL=${EG_EMAIL}
      - EG_PASSWORD=${EG_PASSWORD}
      - EG_OTPKEY=${EG_OTPKEY}
